### ISSUE TITLE
Piercing The Shroud - Brutalisk if cutscenes skipped

### ISSUE THREAD

**Issue by Ziktofel** [Ziktofel/Archipelago-SC2-data#100]
> @MatthewMarinets Ain't this:
> 
> ```
> Piercing the Shroud Freeing the brutalisk doesn't update the doodad, and it can be spawned again (--Phanerus, --Sheen)
> ```
> 
> tied to Cutscene skip option?

Yep, I had skip cutscenes and no_force_camera turned on. I can't speak for Sheen but I expect the same for him. Being able to respawn the brutalisk was information from Sheen, I didn't confirm it.

_Originally posted by @MatthewMarinets in https://github.com/Ziktofel/Archipelago/issues/157#issuecomment-1933075887_

It looks like if the Brutalisk is activated, and the cutscenes are skipped, the cleanup isn't properly executed

**Comment by Ziktofel** [comment]
@EnvyDragon can you look into this?

**Comment by EnvyDragon** [comment]
Looking into it right now, gonna see if I can solve the disappearing chatbox while I'm at it

**Comment by EnvyDragon** [comment]
https://github.com/Ziktofel/Archipelago-SC2-data/pull/101
