### ISSUE TITLE
Creep Tumor Issues

### ISSUE THREAD

**Issue by Magnemania** [Ziktofel/Archipelago-SC2-data#12]
1. When using the Creep Tumor's Spawn Creep Tumor ability, the animation where a tentacle moves from the existing Creep Tumor to the new Creep Tumor's spawn location is skipped.
2.  Inactive Creep Tumors (the ones that can't spawn new creep tumors) should not display on the minimap.

**Comment by Ziktofel** [comment]
1. Fixed
2. Still there

**Comment by Ziktofel** [comment]
Fixed
