### ISSUE TITLE
Viking Magrail Munitions Rename

### ISSUE THREAD

**Issue by Magnemania** [Ziktofel/Archipelago-SC2-data#2]
In all vanilla cases, "Magrail Munitions" refers to adding a blue laser weapon to the upgraded unit.  The "Magrail Munitions" upgrade for Viking does not do this, nor does it mimic the gameplay effect of vanilla use cases (it is not an extra attack as with infantry, and it does not add piercing damage like the Raven's turret).

Since the upgrade does not exist in any of the vanilla campaigns and does not mimic an existing effect, it should given a unique name and icon that better conveys that the upgrade benefits the landed Viking's damage against mechanical units.

Suggested names:
- Voltaic Rounds
- Anti-Mechanical Ordnance
- Lightning Rounds
- Shredder Rounds
- Circuit Breaker Ordnance

Suggested icon:
btn-ability-terran-ignorearmor.dds

**Comment by Ziktofel** [comment]
https://cdn.discordapp.com/attachments/980554570075873300/1159980735797674004/btn-ability-terran-ignorearmor.png?ex=6532ff3e&is=65208a3e&hm=19409ad189acc8209e205cedb78e36cda3c175ff572f1943e93c10d3dc1166f4&

**Comment by Ziktofel** [comment]
![Uploading btn-ability-terran-ignorearmor.png…]()

**Comment by Ziktofel** [comment]
Done
