### ISSUE TITLE
Misc actor data issues

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago-SC2-data#266]
- [x] Fenix from SOA calldown doesn't play the spinning animation properly when spinning. Fenix in Templar's Return works fine
- [x] Zerg air advanced morphs don't play an "entering cocoon" animation when starting their morph. Observed on Viper and morphling -> devourer, others should be checked too
- [x] Protoss Stargate units do a warping-in spell animation on being built from a (non-warp) stargate. This doesn't work for all units. Skylord should be fine after WC PR, Arbiter was observed to be missing this animation.
- [x] Ravager, Corruptor, and Scourge portraits are missing lightdata entries. Other units may be as well, these are the ones I noticed.

**Comment by SirChuckOfTheChuckles** [comment]
Fixed Fenix from SoA calldown, fixed protoss warping-in spell animations

**Comment by Ziktofel** [comment]
Should be already patched
