### ISSUE TITLE
WoL: AP Hatchery worker rally not working

### ISSUE THREAD

**Issue by Salzkorn** [Ziktofel/Archipelago-SC2-data#39]
The ability `AP_RallyHatchery` uses two validators from `Swarm.SC2Mod` (`IsDroneOrOverlord` and `NotDroneAndNotOverlord`), which causes drones spawned at hatcheries in WoL maps to move to the combat rally point instead of the worker rally point.

Example from Great Train Robbery with a Hive plopped down (and player race switched to Zerg for testing):
![SC2_x64_dDh0gSwzVi](https://github.com/Ziktofel/Archipelago-SC2-data/assets/30208051/ecd03b1c-4bf2-4b92-b478-49fe172822cf)

**Comment by Ziktofel** [comment]
That got already fixed IIRC
