### ISSUE TITLE
HotS: Impaler unlock does not grant Greater Hydra Den morph

### ISSUE THREAD

**Issue by EnvyDragon** [Ziktofel/Archipelago-SC2-data#46]
If you have Morph Impaler unlocked, but you don't have Morph Lurker, then Hydralisks will gain the greyed-out morph ability but you'll never be able to actually upgrade your Hydralisk Den to satisfy the requirement. The ability seems to check for Lurker tech and nothing else.

**Comment by Ziktofel** [comment]
Fixed in 7c8e5fc08
