### ISSUE TITLE
WoL - Great Train Robbery 6 Trains location (sometimes?) doesn't send properly

### ISSUE THREAD

**Issue by EnvyDragon** [Ziktofel/Archipelago-SC2-data#49]
Some settings:

-Normal difficulty, skip flags on, WoL/NCO world generated
-Finished the mission without missing a train (got "flawless" check)
-On mission end, "6 trains destroyed" location was still unchecked

**Comment by Ziktofel** [comment]
Did you update the client? The location is in 14+ area

**Comment by EnvyDragon** [comment]
![image](https://github.com/Ziktofel/Archipelago-SC2-data/assets/138727357/83f0c10d-a418-4781-b18d-97b10869d680)
Client and data were updated at the same time, so... probably.

I'll check again a little later tonight to verify.
