### ISSUE TITLE
Another list of misc bugs

### ISSUE THREAD

**Issue by EnvyDragon** [Ziktofel/Archipelago-SC2-data#72]
Bugs:

- [x] Planetfall: Countdown timer and "next launcher arriving here" pings did not disappear after final launcher landed. Observed with skip_cutscenes and kerriganless active. PR FOR FIX: https://github.com/Ziktofel/Archipelago-SC2-data/pull/74
- [x] Planetfall: After the "destroy the dominion bases" cutscene is auto-skipped, Kerrigan was unhidden at base on Kerriganless settings. PR FOR FIX: https://github.com/Ziktofel/Archipelago-SC2-data/pull/74

- [ ] Piercing the Shroud: AP chatbox disappears after reactor explosion

- [ ] Supernova: "Destroy this" ping from opening is not destroyed on cutscene transition (when skip-cutscene flag is active, presumably) (NOTE: Could not reproduce)

- [ ] NCO campaign: Nova sometimes fails to respawn for unknown reasons. Observed on Sudden Strike, Trouble in Paradise, Night Terrors, and Flashpoint; likely a mission-independent issue.

- [ ] Torrasque Ultralisk revive has been observed to fail for unknown reasons

- [x] Guardian Shell has been observed to fail for unknown reasons (possibly a unit death tracking problem?)
-- On Dragoon at least, it's because the behavior isn't present; may be a good idea to find a way to automate this in the future, as there are a good number of behaviors (esp. from co-op) which we don't want to manually apply to every single unit in the game.

- [x] Some LotV missions (Spear of Adun, [expand list when I notice/remember more]) don't automatically set worker rally + make workers harvest
-- Note: this appears to be because certain LotV missions use some manner of "set all nexus rally points" init trigger which doesn't look for AP_Nexus. May help to add a utility method to AP_Player mod that checks for all player-owned instances of AP town hall structures and sets those rallies/starts autoharvesting.

- [ ] Temple of Unification: Titanic warp prism doesn't do anything (it's supposed to move and warp stuff in)

- [ ] Maw of the Void: Mothership still performs hostile triggers even if it's been MC'd
-- probably a good idea to add "AI - disable script control" to the mind control triggers

Polish:

- [ ] NCO (and WoL Mar Sara) missions should probably start the player with a merc compound

- [x] Most LotV missions: Ending the game generates a harmless crash report window - the HotS/NCO fix could be reapplied here

- [x] Supernova cutscene skip is very abrupt, probably needs a fade-out

- [ ] Growing Shadow cutscene skip probably doesn't need that fade-out (let's take it and give it to Supernova instead)

- [ ] Growing Shadow: MCing end protoss should remove them from the unit group that gets checked for stage transition

- [ ] The Infinite Cycle: First holdout; zealots and colossi that get warped in from SW side have silly-looking accelerated animations

**Comment by MatthewMarinets** [comment]
Note the Piercing the Shroud chatbox disappearing has an existing case on the client repo, [#135](https://github.com/Ziktofel/Archipelago/issues/135). Most new bugs are filed to that repo to keep things in one place.

**Comment by MatthewMarinets** [comment]
> Guardian Shell has been observed to fail for unknown reasons (possibly a unit death tracking problem?)

I think the guardian shell buff is attached to each unit type individually, with e.g.
```xml
<BehaviorArray Link="AP_SOAHeroicShieldProcBuff"/>
```
It's only supposed to proc on Protoss units. If it fails, it's likely linked to unit type (or the behaviour could be getting dispelled somehow, but that's less likely.)
