### ISSUE TITLE
Compiled issues from playthrough on sc2-next

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago-SC2-data#8]
Compiling issues discovered from my playthrough last weekend, some of these may already be fixed:
- [x] Some kerrigan voicelines erroneously use the in-egg portrait / voice effect even when kerrigan is still alive. Happened twice when capturing garrisons in infested, and it happened in another mission as a onceoff (forgot which)
- [x] descriptions are missing for console commands `/color`, `/skip_custcenes` and `/disable_forced_camera`
- [x] Using infestor mind-control on an ursadon during a flash freeze instantly freezes them. I can understand this happening for the protoss units I control, but the ursadons are canonically not frozen and that's on display right up until I control them
- [x] If you mind-control an ursadon from an attack-wave on Harvest of Screams, their old AI still kicks in and periodically sends them back to the gather point
![image](https://github.com/Ziktofel/Archipelago-SC2-data/assets/31861583/90d4af28-b9e3-4c49-b746-44ca2defa633)

- [x] I've noticed this a couple of times, including Harvest of Screams and Domination, so probably applies to all hots missions. Drones automatically start harvesting from minerals, but they don't start on vespene. Presumably because the extractor is an AP_extractor, and that screws up the trigger
- [x] on Harvest of Screams, Nafash's base isn't properly frozen. I missed if the buildings had the frozen model, but the overlords were certainly missing it
- [x] Raid Liberator fighter mode (the mobile aa one) doesn't use the same hotkey as normal liberator fighter mode. Raid liberators don't show up in any hotkey configuration menu, so it's not rebindable
- [x] Swarm Queens have the melee Queen spawn creep tumor, which costs 25 energy and has no cooldown. Swarm queen creep tumors normally have a cooldown but no energy cost.
- [x] Spawn banelings doesn't play the baneling unburrow animation
- [x] The Archipelago message box covers up the loss condition timer in Moebius Factor
- [x] (QOL more so than bug) Cyclones have a higher command-card selection priority than spectres, so I need to tab over / have multiple hotkeys to use spectre abilities when cyclones don't really have activateable abilities of their own I'd want to micro
- [x] The reaper jumping sound effect is different / landing sound effect is too loud or possibly unaffected by volume sliders

**Comment by Ziktofel** [comment]
Need to re-test those

**Comment by EnvyDragon** [comment]
Added /skip_cutscene and /disable_forced_camera description text at some point (sorry I forget which pull request but it's there now)

Harvest of Screams non-frozen base bug fix here: https://github.com/Ziktofel/Archipelago-SC2-data/pull/38
